/**
 * Generated with: https://loremipsum.io/
 */
export const loremIpsum = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada bibendum arcu vitae elementum. Senectus et netus et malesuada fames ac turpis egestas integer. Volutpat odio facilisis mauris sit amet massa vitae. Ornare quam viverra orci sagittis eu volutpat. Nunc sed velit dignissim sodales ut. Et malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Vel eros donec ac odio tempor. Vitae elementum curabitur vitae nunc sed velit. A cras semper auctor neque.

Senectus et netus et malesuada fames ac. Mattis vulputate enim nulla aliquet porttitor. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Ipsum dolor sit amet consectetur adipiscing elit. Sit amet commodo nulla facilisi. At varius vel pharetra vel turpis nunc eget lorem dolor. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Gravida dictum fusce ut placerat orci nulla. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. In fermentum et sollicitudin ac orci phasellus egestas. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo.

Urna nunc id cursus metus. Ut faucibus pulvinar elementum integer enim. Viverra nam libero justo laoreet sit. Cras semper auctor neque vitae. Tempor orci dapibus ultrices in. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Ultrices in iaculis nunc sed augue lacus viverra vitae. Vitae et leo duis ut diam quam. Ultricies leo integer malesuada nunc vel risus. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Donec et odio pellentesque diam. Tempor id eu nisl nunc mi. Mauris commodo quis imperdiet massa.
`.trim();